<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
echo "Tools Za.GL\nBuatan Mas IZzamuddin Royhul Firdaus\nAnda Pakai Harus Ada PAssword\n";
if (readline("Masukan Password : ") != "1") {
	die("Salah PAssword")
}
$links = readline("Masukkan Link:");
$ch = curl_init();
//file_get_contents("")
curl_setopt($ch, CURLOPT_URL, $links);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
//curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_REFERER,"https://facebook.com/izz.354");
$headers = array();
$headers[] = 'Authority: zee.gl';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Dnt: 1';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3';
$headers[] = 'Sec-Fetch-Site: none';
//$headers[] = 'Accept-Encoding: gzip, deflate, br';
$headers[] = 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7';
$headers[] = 'Cookie: __cfduid=d12ca9db636f9bea88cec990419f97b011567735913';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_COOKIEJAR, "1");
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}else
{

}
curl_close($ch);
$data = $result;
preg_match_all('/<a href="(.*)" class="btn-3d red">CLICK HERE<\/a>/', $data, $hasil);
$link = $hasil[1][0];

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://za.gl/NEW97');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

//curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_COOKIEJAR, "1");
curl_setopt($ch, CURLOPT_COOKIEFILE, "1");
$headers = array();
$headers[] = 'Authority: za.gl';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'Dnt: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3';
$headers[] = 'Sec-Fetch-Site: cross-site';
$headers[] = 'Referer: https://zee.gl/NEW97';
//$headers[] = 'Accept-Encoding: gzip, deflate, br';
$headers[] = 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7';

//$headers[] = 'Cookie: __cfduid=de9f80040ec49ddf1b146a1d3b7c99d811567735889; csrfToken=39164b6fef6df9489db0a27cc9d5cc70ad403332777b381d0945af2b17fe3b8d3c508095fc2228aa2cb20ff2ad0b91ee9fb35c89d304d3360d3a15ba158b89a4; sls=0; ref=; clickID=; _ga=GA1.2.1751617300.1567735880; _gid=GA1.2.158863295.1567735880; visitor=Q2FrZQ%3D%3D.ZDFiMzUyNGJiYWNlN2E3NjMxYTcxODhiZGQxOTZiYWIzMmQyMDNhNTJkY2FjYzk0OTYzZjA1ODQyZjdhODg1MyC2UcS6j%2FHMIgFiNwhmba21ypNK6Ji2s1gTXlxY8LaMiG7l5zp%2FPdI20W0SQgaRqkpzpc7CMOdmy3Ia%2FiwjA%2FUCCRrhP39%2BOSLqZ06BKwTO; slv=0; AppSession=8rfnh9bvsdiflodd3fpsg626a3; overlay=1; hash=Q2FrZQ%3D%3D.NGJhNGM1MTg2ZmNjNDA1YjU0ZmU3NTJlMDYzNTQwZmRmYWNlNzUwMDJlZTYxMmU4NDkzYWNlM2Y0MzEyNDFhNTog92Uc7jUOfZlKK8ReyEzXcwl8B2n7m52yiSnRsZVtUJDv%2BdvxE0XOwzFDqS4mjAWjUs3SBpgrXdFXJaw0qjM%3D; ab=2';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}else
{
	fwrite(fopen("hasil", "w"), $result);
}
curl_close($ch);

$data = $result;
preg_match_all('<input type="hidden" name="_csrfToken" autocomplete="off" value="(.*)"\/>', $data, $p);
preg_match_all('/<input type="hidden" name="ad_form_data" value="(.*)"\/>/', $data, $oke);
preg_match_all('/<input type="hidden" name="_Token\[fields\]" autocomplete="off" value="(.*)"\/><input type="/', $data, $token);
 //print_r($token);
//$kode = array("nama"=>"nama","kode"=>"kode");
preg_match_all('/<input type="hidden" name="_Token\[unlocked\]" autocomplete="off" value="(.*)"\/>/', $data, $token2);
$q = array('_method'=>"POST","_csrfToken"=>$p[1][0],"ad_form_data"=>$oke[1][0],'_Token[fields]'=>$token[1][0],'_Token[unlocked]'=>$token2[1][0]);
$qj = http_build_query($q);
fwrite(fopen("token", "w"), $qj);
sleep(3);

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://za.gl/links/go');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $qj);
curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
$headers = array();
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Origin: https://za.gl';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36';
$headers[] = 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8';
$headers[] = 'Accept: application/json, text/javascript, */*; q=0.01';
$headers[] = 'Referer: https://za.gl/NEW97';
$headers[] = 'X-Requested-With: XMLHttpRequest';
$headers[] = 'Dnt: 1';
$headers[] = 'Cookie: ab=2';
//curl_setopt($ch, CURLOPT_VERBOSE, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_COOKIEFILE, "1");

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
if (preg_match("/earning/", $result)) {
	echo "=> Berhasil";
}else
{
	echo "=> Gagal";
}